service: florify-simple

provider:
  name: aws
  runtime: python3.9
  region: eu-north-1
  stage: dev
  environment:
    CLIENT_ID: 76i7it21omdm3n80nf9j9dc2oc
    COGNITO_USER_POOL_ID: eu-north-1_i7vhr8PxH
    COGNITO_REGION: eu-north-1
    GARDENS_TABLE: florify-gardens-dev
    BLUEPRINTS_TABLE: florify-blueprints-dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:*
          Resource: "*"
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "*"
        - Effect: Allow
          Action:
            - logs:*
          Resource: "*"

functions:
  # Authentication
  signup:
    handler: signup_handler.handler
    events:
      - http:
          path: signup
          method: post
          cors: true

  login:
    handler: login_handler.handler
    events:
      - http:
          path: login
          method: post
          cors: true

  confirm:
    handler: confirm_handler.handler
    events:
      - http:
          path: confirm
          method: post
          cors: true

  resend:
    handler: resend_handler.handler
    events:
      - http:
          path: resend
          method: post
          cors: true

  # Gardens
  create-garden:
    handler: create_garden_handler.handler
    events:
      - http:
          path: gardens
          method: post
          cors: true

  get-gardens:
    handler: get_gardens_handler.handler
    events:
      - http:
          path: gardens
          method: get
          cors: true

  get-garden:
    handler: get_garden_handler.handler
    events:
      - http:
          path: gardens/{gardenId}
          method: get
          cors: true

  update-garden:
    handler: update_garden_handler.handler
    events:
      - http:
          path: gardens/{gardenId}
          method: put
          cors: true

  delete-garden:
    handler: delete_garden_handler.handler
    events:
      - http:
          path: gardens/{gardenId}
          method: delete
          cors: true

  # Blueprints
  create-blueprint:
    handler: create_blueprint_handler.handler
    events:
      - http:
          path: blueprints
          method: post
          cors: true

  get-blueprint:
    handler: get_blueprint_handler.handler
    events:
      - http:
          path: blueprints/{blueprintId}
          method: get
          cors: true

  get-blueprint-by-garden:
    handler: get_blueprint_by_garden_handler.handler
    events:
      - http:
          path: gardens/{gardenId}/blueprint
          method: get
          cors: true

  update-blueprint:
    handler: update_blueprint_handler.handler
    events:
      - http:
          path: blueprints/{blueprintId}
          method: put
          cors: true

  # Test
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
          cors: true

resources:
  Resources:
    GardensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: florify-gardens-dev
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: gardenId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: gardenId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    BlueprintsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: florify-blueprints-dev
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: blueprintId
            AttributeType: S
          - AttributeName: gardenId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
          - AttributeName: blueprintId
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GardenIdIndex
            KeySchema:
              - AttributeName: gardenId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
        BillingMode: PAY_PER_REQUEST